// <auto-generated />
using System;
using ChampBot.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChampBot.Migrations
{
    [DbContext(typeof(BotDb))]
    [Migration("20250920090425_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ChampBot.Domain.UserConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChallengeActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChallengeStartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DotaAccountId32")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalWins")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LossesSoFar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingAction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemainingWins")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SteamId64")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TelegramUserid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinsSoFar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
